spring:
  application:
    name: eresto
    description: Application de commande en ligne
    basedir: ${user.home}/.${spring.application.name}
  datasource:
    database: dzoenamdb
    hostname: localhost
    port: 5432
    username: francis
    password: africa
    url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: "SELECT 1"
      max-lifetime: 1800000
      idle-timeout: 600000
      leak-detection-threshold: 60000
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql

